version: "3"

services:
  laravel-app-app:
    container_name: laravel-app-app
    build: ./docker/php
    volumes:
      - .:/var/www/html
    depends_on:
      - laravel-app-db

  laravel-app-nginx:
    container_name: laravel-app-nginx
    image: nginx:1.20-alpine
    ports:
      - 82:80
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel-app-app

  laravel-app-db:
    container_name: laravel-app-mysql
    image: mysql:8.0
    platform: linux/amd64
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/logs:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=laravel_app
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Tokyo  
    ports:
      - 3306:3306

  laravel-app-build-npm:
    container_name: laravel-app-build-npm
    image: node:18.16.0-alpine
    tty: true
    working_dir: /var/www
    volumes:
      - .:/var/www

  laravel-app-build-composer:
    container_name: laravel-app-build-composer
    build: ./docker/composer
    tty: true
    volumes:
      - .:/var/www/html

  mailhog:
    image: mailhog/mailhog
    ports:
      - target: 8025
        published: ${MAILHOG_PUBLISHED_PORT:-8025}
        protocol: tcp
        mode: host
